version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        IMAGE: python:3.11
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    networks:
      - internal

  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: LocalPasswordOnly
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - internal

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - internal

  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - internal

  cockroach:
    image: cockroachdb/cockroach:v23.1.11
    restart: unless-stopped
    command: start-single-node --insecure
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    networks:
      - internal

volumes:
  postgres-data:
  redis-data:
  mongo-data:
  cockroach-data:

networks:
  internal:
