services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        IMAGE: python:3.11
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    networks:
      - internal

  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: LocalPasswordOnly
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - internal

  
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    networks:
      - internal
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - internal

  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - internal

  cockroach:
    image: cockroachdb/cockroach:v23.1.11
    restart: unless-stopped
    command: start-single-node --insecure --advertise-addr=0.0.0.0
    ports:
      - "8080:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    networks:
      - internal

  neo4j:
    image: neo4j:5.19
    restart: unless-stopped
    environment:
      NEO4J_AUTH: neo4j/testpassword
      NEO4J_server_config_strict__validation_enabled: false
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data
    networks:
      - internal

volumes:
  postgres-data:
  redis-data:
  mongo-data:
  cockroach-data:
  neo4j-data:
  pgadmin-data:

networks:
  internal:
